import { Router } from 'express'
import {getTasks, createTask,getTask, deleteTask,updateTask,countTask} from '../controllers/tasks.controller'

const router = Router()

/**
 * @swagger
 * components:
 *  schemas: 
 *    Task: 
 *      type: object
 *      properties:
 *         id: 
 *            type: string
 *            description: id autogenerated
 *         name:
 *             type: string
 *             description: task name
 *         description: 
 *             type: string
 *             description: task description
 *      required:
 *        - name
 *        - description
 *      example:
 *        id: WfXYoXkFnuGKCL3S3hjdo
 *        name: task name
 *        description: description task
 */

/**
 * @swagger
 * /tasks:
 *  get:
 *    summary: Return a tasks list
 *    responses: 
 *      200:
 *        description: the list of tasks 
 *        content:
 *         application/json:
 *           schema: 
 *              type: array
 *              items: 
 *                $ref: '#/components/schemas/Task'
 */

router.get('/tasks', getTasks)

/**
 * @swagger
 * /tasks/count:
 *  get:
 *    summary: Return task count
 *    responses:
 *      200:
 *        description: tasks count
 *        content:
 *          schema: 
 *             type: integer
 */

router.get('/tasks/count', countTask)
router.post('/tasks', createTask)
router.get('/tasks/:id', getTask)
router.delete('/tasks/:id', deleteTask)
router.put('/tasks/:id', updateTask)

export default router